import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: [
    'src/dimensions.ts',
    'src/interval.ts',
    'src/length.ts',
    'src/pipe.ts',
    'src/solution.ts',
    'src/utils.ts',
    'src/curve/index.ts',
    'src/curve/cubic2d.ts',
    'src/curve/linear2d.ts',
    'src/curve/quadratic2d.ts',
    'src/matrix/index.ts',
    'src/matrix/matrix2x2.ts',
    'src/matrix/matrix3x3.ts',
    'src/matrix/matrix4x4.ts',
    'src/path/index.ts',
    'src/path/cubic2d.ts',
    'src/path/linear2d.ts',
    'src/path/quadratic2d.ts',
    'src/polynomial/index.ts',
    'src/polynomial/cubic.ts',
    'src/polynomial/linear.ts',
    'src/polynomial/quadratic.ts',
    'src/splines/index.ts',
    'src/splines/basis2d.ts',
    'src/splines/bezier2d.ts',
    'src/splines/cardinal2d.ts',
    'src/splines/hermite2d.ts',
    'src/vector/index.ts',
    'src/vector/vector2.ts',
    'src/vector/vector3.ts',
    'src/vector/vector4.ts',
  ],
  format: 'esm',
  dts: true,
  sourcemap: true,
  target: 'es2022',
  clean: true,
  outputOptions: {
    entryFileNames: '[name].mjs',
    chunkFileNames: 'shared/[name]-[hash].mjs',
  },
  tsconfig: './tsconfig.json',
})
